import { primitives } from "./internal/primitives.js";

// These are semantic roles, not aliases for public primitive scales. A metric
// is added only when a governed consumer has an intentional use for it.
export const semanticShared = {
  type: {
    display: {
      family: "display",
      size: primitives.font.size["4xl"],
      lineHeight: 1.05,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.tight,
    },
    heading: {
      family: "display",
      size: primitives.font.size["3xl"],
      lineHeight: 1.12,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.tight,
    },
    title: {
      family: "display",
      size: primitives.font.size["2xl"],
      lineHeight: 1.2,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.normal,
    },
    subtitle: {
      family: "body",
      size: primitives.font.size.xl,
      lineHeight: 1.3,
      weight: primitives.font.weight.semibold,
      tracking: primitives.font.tracking.normal,
    },
    bodyLarge: {
      family: "body",
      size: primitives.font.size.lg,
      lineHeight: 1.5,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.normal,
    },
    body: {
      family: "body",
      size: primitives.font.size.md,
      lineHeight: 1.5,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.normal,
    },
    bodySmall: {
      family: "body",
      size: primitives.font.size.sm,
      lineHeight: 1.45,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.normal,
    },
    label: {
      family: "body",
      size: primitives.font.size.sm,
      lineHeight: 1.3,
      weight: primitives.font.weight.semibold,
      tracking: primitives.font.tracking.label,
    },
    caption: {
      family: "body",
      size: primitives.font.size.xs,
      lineHeight: 1.4,
      weight: primitives.font.weight.medium,
      tracking: primitives.font.tracking.label,
    },
    overline: {
      family: "body",
      size: primitives.font.size["2xs"],
      lineHeight: 1.3,
      weight: primitives.font.weight.bold,
      tracking: primitives.font.tracking.caps,
    },
    code: {
      family: "mono",
      size: 13,
      lineHeight: 1.5,
      weight: primitives.font.weight.regular,
      tracking: primitives.font.tracking.tight,
    },
    data: {
      family: "mono",
      size: primitives.font.size.xs,
      lineHeight: 1.45,
      weight: primitives.font.weight.medium,
      tracking: primitives.font.tracking.normal,
    },
  },
  boundary: { thickness: primitives.borderWidth.thin },
  control: {
    height: { default: 44, large: 52 },
    radius: primitives.radius.md,
    paddingInline: primitives.space.md,
    gap: primitives.space.xs,
    labelWeight: primitives.font.weight.semibold,
  },
  field: {
    height: 52,
    paddingInline: primitives.space.md,
    gap: primitives.space.xs,
    labelMargin: primitives.space.lg,
  },
  target: { minimum: 44 },
  list: { rowMinimum: 48 },
  surface: {
    radius: {
      default: primitives.radius.none,
      soft: primitives.radius.md,
      featured: primitives.radius.xl,
      hero: primitives.radius["2xl"],
    },
  },
  badge: { radius: primitives.radius.xs },
  pill: { radius: primitives.radius.full },
  divider: { thickness: primitives.borderWidth.thin },
  focus: { width: primitives.borderWidth.strong, offset: 2 },
  interaction: { disabled: { opacity: primitives.opacity.disabled } },
  brandMark: {
    size: 36,
    radius: primitives.radius.full,
    weight: primitives.font.weight.bold,
    tracking: primitives.font.tracking.label,
  },
  motion: {
    feedback: { duration: primitives.duration.fast, easing: "standard" },
    exit: { duration: primitives.duration.normal, easing: "standard" },
    enter: { duration: primitives.duration.deliberate, easing: "out" },
    layout: { duration: primitives.duration.slow, easing: "inOut" },
    reduced: { duration: primitives.duration.instant },
  },
} as const;
