SELECT format(
  'CREATE ROLE %I LOGIN PASSWORD %L',
  :'reader_user',
  :'reader_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'reader_user')
\gexec

SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION',
  :'reader_user',
  :'reader_password'
)
\gexec
SELECT format(
  'ALTER ROLE %I SET default_transaction_read_only = on',
  :'reader_user'
)
\gexec

SELECT format('REVOKE ALL ON DATABASE %I FROM %I', current_database(), :'reader_user')
\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'reader_user')
\gexec

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'mutation_user', :'mutation_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'mutation_user')
\gexec
SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION',
  :'mutation_user',
  :'mutation_password'
)
\gexec
SELECT format('REVOKE ALL ON DATABASE %I FROM %I', current_database(), :'mutation_user')
\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'mutation_user')
\gexec
SELECT format('CREATE SCHEMA IF NOT EXISTS demo AUTHORIZATION %I', :'owner_user')
\gexec
CREATE TABLE IF NOT EXISTS demo.metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  value integer NOT NULL
);
INSERT INTO demo.metrics (id, label, value)
VALUES (1, 'dummy42', 42)
ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, value = EXCLUDED.value;
SELECT format('ALTER TABLE demo.metrics OWNER TO %I', :'mutation_user')
\gexec
SELECT format('REVOKE ALL ON SCHEMA demo FROM %I', :'mutation_user')
\gexec
SELECT format('GRANT USAGE ON SCHEMA demo TO %I', :'mutation_user')
\gexec
SELECT format('REVOKE CREATE ON SCHEMA demo FROM %I', :'mutation_user')
\gexec

SELECT format('REVOKE ALL ON SCHEMA demo FROM %I', :'reader_user')
\gexec
SELECT format('GRANT USAGE ON SCHEMA demo TO %I', :'reader_user')
\gexec
SELECT format('GRANT SELECT ON ALL TABLES IN SCHEMA demo TO %I', :'reader_user')
\gexec
SELECT format(
  'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA demo GRANT SELECT ON TABLES TO %I',
  :'owner_user',
  :'reader_user'
)
\gexec

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'writer_user', :'writer_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'writer_user')
\gexec
SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION',
  :'writer_user',
  :'writer_password'
)
\gexec
SELECT format('REVOKE ALL ON DATABASE %I FROM %I', current_database(), :'writer_user')
\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'writer_user')
\gexec
SELECT format('REVOKE ALL ON SCHEMA demo FROM %I', :'writer_user')
\gexec
SELECT format('GRANT USAGE ON SCHEMA demo TO %I', :'writer_user')
\gexec
SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA demo TO %I', :'writer_user')
\gexec
SELECT format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA demo TO %I', :'writer_user')
\gexec
SELECT format('REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA demo FROM %I', :'writer_user')
\gexec

SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'mcp_user', :'mcp_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'mcp_user')
\gexec
SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION',
  :'mcp_user',
  :'mcp_password'
)
\gexec
SELECT format('REVOKE ALL ON DATABASE %I FROM %I', current_database(), :'mcp_user')
\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'mcp_user')
\gexec
SELECT format('GRANT USAGE ON SCHEMA public TO %I', :'mcp_user')
\gexec
SELECT format('REVOKE ALL PRIVILEGES ON TABLE public.data_sources, public.data_source_credentials FROM %I', :'mcp_user')
WHERE to_regclass('public.data_sources') IS NOT NULL
  AND to_regclass('public.data_source_credentials') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT (id, connector_type, name, status, config, original_filename, mime_type, file_size_bytes, azure_blob_name, azure_etag, azure_cleanup_status, azure_cleanup_etag, azure_cleanup_attempts, azure_cleanup_completed_at, azure_cleanup_error_code, processing_message, created_at, updated_at, deleted_at) ON TABLE public.data_sources TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.data_sources') IS NOT NULL
\gexec
SELECT format(
  'REVOKE ALL PRIVILEGES ON TABLE public.chat_sessions, public.chat_session_data_sources FROM %I',
  :'mcp_user'
)
WHERE to_regclass('public.chat_sessions') IS NOT NULL
  AND to_regclass('public.chat_session_data_sources') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT (id, status, deleted_at) ON TABLE public.chat_sessions TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.chat_sessions') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT (chat_session_id, data_source_id) ON TABLE public.chat_session_data_sources TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.chat_session_data_sources') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT (data_source_id, ciphertext, iv, auth_tag, encryption_version, revision, updated_at) ON TABLE public.data_source_credentials TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.data_source_credentials') IS NOT NULL
\gexec
SELECT format(
  'REVOKE ALL PRIVILEGES ON TABLE public.sql_change_sets, public.sql_change_executions FROM %I',
  :'mcp_user'
)
WHERE to_regclass('public.sql_change_sets') IS NOT NULL
  AND to_regclass('public.sql_change_executions') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT, INSERT, UPDATE ON TABLE public.sql_change_sets, public.sql_change_executions TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.sql_change_sets') IS NOT NULL
  AND to_regclass('public.sql_change_executions') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT, INSERT, UPDATE ON TABLE public.analysis_artifacts TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.analysis_artifacts') IS NOT NULL
\gexec
SELECT format(
  'GRANT SELECT, INSERT ON TABLE public.analysis_artifact_lineage TO %I',
  :'mcp_user'
)
WHERE to_regclass('public.analysis_artifact_lineage') IS NOT NULL
\gexec
